apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc 
  namespace: web-app
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi  
  storageClassName: efs-sc 